# Identificadores obligatorios (Esto le dice a SonarCloud a dónde mandar los resultados)
sonar.projectKey=c1c9ca639cc2f2821d50937598de620f37a0d2d3
sonar.organization=lautilovato

# Directorios a analizar (Normalmente es src o . para la raíz entera)
sonar.sources=src

# Archivos y carpetas a excluir del escaneo (muy importante para no escanear librerías o dependencias)
sonar.exclusions=node_modules,dist,build,coverage

# Si usas JavascriptTypescript y tienes tests, aquí le dices dónde está el reporte de cobertura (opcional)
# sonar.javascript.lcov.reportPaths=coveragelcov.info

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
