/**
 * Nombre de país (tal como lo entrega Football-Data.org) → código de bandera (research #7).
 *
 * Función pura: sin NestJS, sin inyección, sin base de datos (constitución §7, excepción de
 * utilidades puras).
 *
 * Por qué existe: la entidad `Player` guarda `nationality` como el NOMBRE del país
 * ("England", "Argentina"), pero el componente de carta arma la URL de la bandera con un
 * código alpha-2 (`flagcdn.com/w160/{code}.png`). Sin esta traducción, toda bandera quedaría
 * rota. Se normaliza acá y no en el cliente porque es el dato crudo de un proveedor externo,
 * y porque así la grilla y el detalle comparten una sola fuente.
 *
 * Las selecciones británicas son la excepción que obliga a la tabla explícita: no existen en
 * ISO 3166-1 alpha-2 y flagcdn las sirve como subdivisiones, formato que el propio componente
 * documenta en sus tipos.
 *
 * Cobertura: los países con presencia real en las 5 ligas del catálogo. Un país ausente
 * devuelve null y la carta simplemente no dibuja bandera — nunca una imagen rota.
 */

const CODES: Record<string, string> = {
  // Subdivisiones británicas (no son alpha-2)
  england: 'gb-eng',
  scotland: 'gb-sct',
  wales: 'gb-wls',
  'northern ireland': 'gb-nir',

  // Europa
  albania: 'al',
  andorra: 'ad',
  armenia: 'am',
  austria: 'at',
  azerbaijan: 'az',
  belarus: 'by',
  belgium: 'be',
  'bosnia and herzegovina': 'ba',
  bulgaria: 'bg',
  croatia: 'hr',
  cyprus: 'cy',
  czechia: 'cz',
  'czech republic': 'cz',
  denmark: 'dk',
  estonia: 'ee',
  'faroe islands': 'fo',
  finland: 'fi',
  france: 'fr',
  georgia: 'ge',
  germany: 'de',
  gibraltar: 'gi',
  greece: 'gr',
  hungary: 'hu',
  iceland: 'is',
  ireland: 'ie',
  italy: 'it',
  kosovo: 'xk',
  latvia: 'lv',
  liechtenstein: 'li',
  lithuania: 'lt',
  luxembourg: 'lu',
  malta: 'mt',
  moldova: 'md',
  montenegro: 'me',
  netherlands: 'nl',
  'north macedonia': 'mk',
  norway: 'no',
  poland: 'pl',
  portugal: 'pt',
  romania: 'ro',
  russia: 'ru',
  'san marino': 'sm',
  serbia: 'rs',
  slovakia: 'sk',
  slovenia: 'si',
  spain: 'es',
  sweden: 'se',
  switzerland: 'ch',
  turkey: 'tr',
  türkiye: 'tr',
  ukraine: 'ua',

  // América
  argentina: 'ar',
  bolivia: 'bo',
  brazil: 'br',
  canada: 'ca',
  chile: 'cl',
  colombia: 'co',
  'costa rica': 'cr',
  cuba: 'cu',
  curacao: 'cw',
  'dominican republic': 'do',
  ecuador: 'ec',
  'el salvador': 'sv',
  grenada: 'gd',
  guatemala: 'gt',
  haiti: 'ht',
  honduras: 'hn',
  jamaica: 'jm',
  mexico: 'mx',
  panama: 'pa',
  paraguay: 'py',
  peru: 'pe',
  suriname: 'sr',
  'trinidad and tobago': 'tt',
  'united states': 'us',
  usa: 'us',
  uruguay: 'uy',
  venezuela: 've',

  // África
  algeria: 'dz',
  angola: 'ao',
  benin: 'bj',
  'burkina faso': 'bf',
  burundi: 'bi',
  cameroon: 'cm',
  'cape verde': 'cv',
  'central african republic': 'cf',
  chad: 'td',
  comoros: 'km',
  congo: 'cg',
  'dr congo': 'cd',
  'democratic republic of the congo': 'cd',
  egypt: 'eg',
  'equatorial guinea': 'gq',
  gabon: 'ga',
  gambia: 'gm',
  ghana: 'gh',
  guinea: 'gn',
  'guinea-bissau': 'gw',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  kenya: 'ke',
  liberia: 'lr',
  libya: 'ly',
  madagascar: 'mg',
  mali: 'ml',
  mauritania: 'mr',
  morocco: 'ma',
  mozambique: 'mz',
  namibia: 'na',
  niger: 'ne',
  nigeria: 'ng',
  rwanda: 'rw',
  senegal: 'sn',
  'sierra leone': 'sl',
  somalia: 'so',
  'south africa': 'za',
  sudan: 'sd',
  tanzania: 'tz',
  togo: 'tg',
  tunisia: 'tn',
  uganda: 'ug',
  zambia: 'zm',
  zimbabwe: 'zw',

  // Asia y Oceanía
  afghanistan: 'af',
  australia: 'au',
  bahrain: 'bh',
  bangladesh: 'bd',
  china: 'cn',
  'china pr': 'cn',
  'hong kong': 'hk',
  india: 'in',
  indonesia: 'id',
  iran: 'ir',
  iraq: 'iq',
  israel: 'il',
  japan: 'jp',
  jordan: 'jo',
  kazakhstan: 'kz',
  kuwait: 'kw',
  lebanon: 'lb',
  malaysia: 'my',
  'new zealand': 'nz',
  'north korea': 'kp',
  oman: 'om',
  pakistan: 'pk',
  palestine: 'ps',
  philippines: 'ph',
  qatar: 'qa',
  'saudi arabia': 'sa',
  singapore: 'sg',
  'south korea': 'kr',
  'korea republic': 'kr',
  syria: 'sy',
  thailand: 'th',
  'united arab emirates': 'ae',
  uzbekistan: 'uz',
  vietnam: 'vn',
};

export function nationalityCode(nationality: string | null | undefined): string | null {
  if (!nationality) return null;
  return CODES[nationality.trim().toLowerCase()] ?? null;
}
